"""
Generate cross-runtime .isotrieve fixture files.

Fits each mapping type in Python, saves .isotrieve files, and writes
a companion JSON with input vectors and expected transform outputs
so the TypeScript test can load and compare.

Usage:
    cd isotrieve-npm/packages/core
    python src/__tests__/gen_xruntime_fixtures.py
"""

import json
import os
import numpy as np
from isotrieve.mapping.linear import (
    RidgeMapping,
    OrthogonalProcrustesMapping,
    ProcrustesDiagMapping,
    LowRankAffineMapping,
)

OUT_DIR = os.path.join(os.path.dirname(__file__), "fixtures", "xruntime")
os.makedirs(OUT_DIR, exist_ok=True)


def rng(seed=42):
    return np.random.RandomState(seed)


def make_data(n, d_src, d_tgt, seed=42):
    r = rng(seed)
    X = r.randn(n, d_src).astype(np.float64)
    W_true = r.randn(d_src, d_tgt) * 0.1
    Y = X @ W_true + r.randn(n, d_tgt) * 0.01
    return X, Y


def save_mapping(name, mapping, X, Y, extra=None):
    """Save .isotrieve file and companion metadata JSON."""
    path = os.path.join(OUT_DIR, f"{name}.isotrieve")
    mapping.save(path)

    # Apply to first 10 vectors for comparison
    X_test = X[:10]
    Y_test = Y[:10]
    mapped = mapping.transform(X_test)
    if hasattr(mapping, 'inverse_transform') and mapping._W_inv is not None:
        inv = mapping.inverse_transform(mapped)
    else:
        inv = None

    meta = {
        "mapping_type": name.split("_")[0] if "_" in name else name,
        "d_src": int(X.shape[1]),
        "d_tgt": int(Y.shape[1]),
        "n_test": 10,
        "X_test": X_test.tolist(),
        "Y_test": Y_test.tolist(),
        "mapped": mapped.tolist() if isinstance(mapped, np.ndarray) else [m.tolist() for m in mapped],
        "inverse": inv.tolist() if inv is not None and isinstance(inv, np.ndarray) else ([i.tolist() for i in inv] if inv is not None else None),
    }
    if extra:
        meta.update(extra)

    with open(os.path.join(OUT_DIR, f"{name}.json"), "w") as f:
        json.dump(meta, f)

    print(f"  Saved {name}: .isotrieve ({os.path.getsize(path)} bytes) + .json")


def main():
    print("Generating cross-runtime fixtures...")

    # --- Ridge (with bias) ---
    print("\n1. RidgeMapping (with bias)")
    X, Y = make_data(100, 6, 4, seed=10)
    ridge = RidgeMapping(alpha=1.0, bias=True, seed=0)
    ridge.fit(X, Y)
    save_mapping("ridge_bias", ridge, X, Y)

    # --- Ridge (no bias) ---
    print("\n2. RidgeMapping (no bias)")
    X, Y = make_data(100, 6, 4, seed=11)
    ridge_nb = RidgeMapping(alpha=0.1, bias=False, seed=0)
    ridge_nb.fit(X, Y)
    save_mapping("ridge_nobias", ridge_nb, X, Y)

    # --- Ridge cross-dimension ---
    print("\n3. RidgeMapping (cross-dimension)")
    X, Y = make_data(100, 8, 3, seed=12)
    ridge_cd = RidgeMapping(alpha=1.0, bias=True, seed=0)
    ridge_cd.fit(X, Y)
    save_mapping("ridge_crossdim", ridge_cd, X, Y)

    # --- OrthogonalProcrustes ---
    print("\n4. OrthogonalProcrustesMapping")
    X, Y = make_data(100, 5, 5, seed=13)
    proc = OrthogonalProcrustesMapping(seed=0)
    proc.fit(X, Y)
    save_mapping("procrustes", proc, X, Y)

    # --- ProcrustesDiag ---
    print("\n5. ProcrustesDiagMapping")
    X, Y = make_data(100, 5, 5, seed=14)
    proc_diag = ProcrustesDiagMapping(seed=0)
    proc_diag.fit(X, Y)
    save_mapping("procrustes_diag", proc_diag, X, Y)

    # --- LowRankAffine ---
    print("\n6. LowRankAffineMapping")
    X, Y = make_data(100, 6, 4, seed=15)
    lr = LowRankAffineMapping(alpha=1.0, rank=3, bias=True, seed=0)
    lr.fit(X, Y)
    save_mapping("lowrank", lr, X, Y)

    # --- Write manifest ---
    manifest = {
        "mappings": [
            "ridge_bias",
            "ridge_nobias",
            "ridge_crossdim",
            "procrustes",
            "procrustes_diag",
            "lowrank",
        ],
        "format_version": 2,
        "note": "Generated by Python isotrieve for cross-runtime testing",
    }
    with open(os.path.join(OUT_DIR, "manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)

    print(f"\nAll fixtures written to {OUT_DIR}/")


if __name__ == "__main__":
    main()
